name: build and update pages
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build
      
