name: build and update pages
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build
      - uses: actions/setup-node@v4
        with:
          node-version: 'v18.19.1'
      - run: NODE_OPTIONS=--openssl-legacy-provider npm install
        working-directory: www/
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run build
        working-directory: www/
      - run: ls -la www/dist/
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: github-pages 
          FOLDER: www/dist/ 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}" 
    
